SCR_PlayerCommandsConfig {
 m_aCommands {
  S7R_SetMarkerCommand "{65AA74FC651FEE04}" {
   m_sCommandName "SetSupplyMarker"
   m_sCommandDisplayName "#S7R-SuppSys_SetSupplyMarker"
   m_sIconName "searchAndDestroyCommandAlt"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_bShowPreview 1
   m_eMarkerType SupplyDropMarker
  }
  S7R_CallSupplyCommand "{65AA74FDD09FD15B}" {
   m_sCommandName "InfSupplies1"
   m_sCommandDisplayName "Call Infantry Supplies (x1)"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType InfantrySupply
   m_iAmount MATSupply
  }
 }
}