SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{65A9434F43FC50EA}" {
  m_aElements {
   SCR_PlayerCommandingMenuCategoryElement "{65AA74F7F0CBDC9F}" {
    m_sCategoryDisplayText "Designate Marker"
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{65AA74FE66A19ECF}" {
      m_sCommandName "SetSupplyMarker"
     }
    }
    m_sImageset "{2EFEA2AF1F38E7F0}UI/Textures/Icons/icons_wrapperUI-64.imageset"
    m_sIconName "searchAndDestroyCommandAlt"
    m_bShowOnMap 1
   }
   SCR_PlayerCommandingMenuCategoryElement "{65AA74F07FC74481}" {
    m_sCategoryDisplayText "Call Supplies"
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{65AA74FE730E79DB}" {
      m_sCommandName "InfSupplies1"
     }
    }
    m_sImageset "{2EFEA2AF1F38E7F0}UI/Textures/Icons/icons_wrapperUI-64.imageset"
    m_sIconName "supplies"
    m_bShowOnMap 1
   }
  }
 }
}