SCR_PlayerCommandsConfig {
 m_aCommands {
  S7R_SetMarkerCommand "{65AA74FC651FEE04}" {
   m_sCommandName "SetSupplyMarker"
   m_sCommandDisplayName "#S7R-SuppSys_SetSupplyMarker"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_bShowPreview 1
   m_eMarkerType SupplyDropMarker
  }
  S7R_SetMarkerCommand "{65AC7E9A52BAB8DC}" {
   m_sCommandName "SetMortarMarker"
   m_sCommandDisplayName "#S7R-SuppSys_SetMortarMarker"
   m_sImageset "{3262679C50EF4F01}UI/Textures/Icons/icons_wrapperUI.imageset"
   m_sIconName "grenade"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 2
   m_bShowPreview 1
   m_eMarkerType MortarMarker
  }
  S7R_SetMarkerCommand "{65AC7E9AB87C300D}" {
   m_sCommandName "SetArtilleryMarker"
   m_sCommandDisplayName "#S7R-SuppSys_SetArtMarker"
   m_sImageset "{3262679C50EF4F01}UI/Textures/Icons/icons_wrapperUI.imageset"
   m_sIconName "artilleryFireMission"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 3
   m_bShowPreview 1
   m_eMarkerType ArtilleryMarker
  }
  S7R_CallSupplyCommand "{65AA74FDD09FD15B}" {
   m_sCommandName "InfSupplies1"
   m_sCommandDisplayName "Call Infantry Supplies (x1)"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType InfantrySupply
   m_iAmount MATSupply
  }
  S7R_CallSupplyCommand "{65AC7E9ADC60EB78}" {
   m_sCommandName "InfSupplies2"
   m_sCommandDisplayName "Call Infantry Supplies (x2)"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType InfantrySupply
   m_iAmount HATSupply
  }
  S7R_CallSupplyCommand "{65AC7E9928B77CF9}" {
   m_sCommandName "InfSupplies3"
   m_sCommandDisplayName "Call Infantry Supplies (x3)"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType InfantrySupply
   m_iAmount MMGSupply
  }
  S7R_CallSupplyCommand "{65AC7E9924FD324E}" {
   m_sCommandName "MATSupplies"
   m_sCommandDisplayName "Call MAT Supplies"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType MATSupply
   m_iAmount MATSupply
  }
  S7R_CallSupplyCommand "{65AC7E837D3CFD3A}" {
   m_sCommandName "HATSupplies"
   m_sCommandDisplayName "Call HAT Supplies"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType HATSupply
   m_iAmount MATSupply
  }
  S7R_CallSupplyCommand "{65AC7E8343EE8095}" {
   m_sCommandName "MMGSupplies"
   m_sCommandDisplayName "Call MMG Supplies"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType MMGSupply
   m_iAmount MATSupply
  }
  S7R_CallSupplyCommand "{65AC7E8356CB740D}" {
   m_sCommandName "MortarSupplies"
   m_sCommandDisplayName "Call MMG Supplies"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType MortarSupply
   m_iAmount MATSupply
  }
  S7R_CallSupplyCommand "{65AC7E839F0D2A55}" {
   m_sCommandName "ConstructionSupplies"
   m_sCommandDisplayName "Call Construction Supplies"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType ConstructionSupply
   m_iAmount MATSupply
  }
  S7R_CallSupplyCommand "{65AC7E83E96CFFA2}" {
   m_sCommandName "MedicalSupplies"
   m_sCommandDisplayName "Call Medical Supplies"
   m_sIconName "supplies"
   m_eRequiredRank PRIVATE
   m_bShowOnMap 1
   m_iGestureID 1
   m_eSupplyType MedicalSupply
   m_iAmount MATSupply
  }
 }
}