SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{65A9434F43FC50EA}" {
  m_aElements {
   SCR_PlayerCommandingMenuCategoryElement "{65AA74F7F0CBDC9F}" {
    m_sCategoryDisplayText "Designate Marker"
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{65AA74FE66A19ECF}" {
      m_sCommandName "SetSupplyMarker"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E9AA2D22D58}" {
      m_sCommandName "SetMortarMarker"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E9AA033B7D9}" {
      m_sCommandName "SetArtilleryMarker"
     }
    }
    m_sImageset "{2EFEA2AF1F38E7F0}UI/Textures/Icons/icons_wrapperUI-64.imageset"
    m_sIconName "searchAndDestroyCommandAlt"
    m_bShowOnMap 1
   }
   SCR_PlayerCommandingMenuCategoryElement "{65AA74F07FC74481}" {
    m_sCategoryDisplayText "Call Supplies"
    m_aElements {
     SCR_PlayerCommandingMenuCommand "{65AA74FE730E79DB}" {
      m_sCommandName "InfSupplies1"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E9CC22CD6F0}" {
      m_sCommandName "InfSupplies2"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E9CC6ACC4D3}" {
      m_sCommandName "InfSupplies3"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E83FACCA420}" {
      m_sCommandName "MATSupplies"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E83FC2D5800}" {
      m_sCommandName "HATSupplies"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E83F030AD31}" {
      m_sCommandName "MMGSupplies"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E83CF68C749}" {
      m_sCommandName "MortarSupplies"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E83F5CC11E4}" {
      m_sCommandName "ConstructionSupplies"
     }
     SCR_PlayerCommandingMenuCommand "{65AC7E83C6B9097C}" {
      m_sCommandName "MedicalSupplies"
     }
    }
    m_sImageset "{2EFEA2AF1F38E7F0}UI/Textures/Icons/icons_wrapperUI-64.imageset"
    m_sIconName "supplies"
    m_bShowOnMap 1
   }
  }
 }
}