SCR_BriefingMenuConfig {
 m_aGameModeHints {
  SCR_HintUIInfo "{65BB5983E51C5618}" {
   Name "ame somethingn"
   Description "What does htis do"
  }
 }
 m_aWinConditions {
  SCR_BriefingVictoryCondition "{65BB598345083B36}" {
   victoryCondition CUSTOM
   name "Capture the nearby towns"
   description "Capture and Secure Meaux and St. Philippe"
  }
 }
}