StringTable {
 ItemClassName "DefaultStringTableItem"
 Items {
  DefaultStringTableItem "{65A55B46D5294FF3}" {
   Id "S7R-SuppSys_SetArtMarker"
   Target_en_us "Designate Artillery Target"
  }
  DefaultStringTableItem "{65A55B46D949AF13}" {
   Id "S7R-SuppSys_SetMortarMarker"
   Target_en_us "Designate Mortar Target"
  }
  DefaultStringTableItem "{65A55B4634A7454D}" {
   Id "S7R-SuppSys_SetSupplyMarker"
   Target_en_us "Designate Supply Dropzone"
  }
 }
}