StringTable {
 ItemClassName "DefaultStringTableItem"
 Items {
  DefaultStringTableItem "{65929746A208A76A}" {
   Id "S7R-DeployFOB"
   Target_en_us "Deploy FOB"
  }
  DefaultStringTableItem "{65929746A8DA6869}" {
   Id "S7R-DeployRally"
   Target_en_us "Deploy Rally"
  }
  DefaultStringTableItem "{6592974AD5745ADF}" {
   Id "S7R-FireSupportCategory"
   Target_en_us "Fire Support"
  }
  DefaultStringTableItem "{6592974670D3D2F5}" {
   Id "S7R-Name"
   Target_en_us "7th Ranger Group"
  }
  DefaultStringTableItem "{65929745788F17D4}" {
   Id "S7R-Open7RMenu"
   Target_en_us "Open 7R Menu"
  }
  DefaultStringTableItem "{65929746588EFF43}" {
   Id "S7R-ShortName"
   Target_en_us "7R"
  }
 }
}