ActionManager {
 Contexts {
  ActionContext CharacterGeneralContext {
   Actions {
    Action Open7RMenu {
     InputSource InputSourceSum "{65A95C5EA335091E}" {
      FilterPreset "hold"
      Sources {
       InputSourceValue "{65A95C5EA46C4F00}" {
        Input "keyboard:KC_H"
       }
      }
     }
    }
   }
  }
 }
}