SCR_SaveArsenalLoadout {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AD14F4972CD43C}" {
  Name "#S7R-Loadouts_SaveLoadout"
  m_sIconName "save"
 }
 ActionTitle "SaveLoadout"
 "Sort Priority" 100
 m_bAllowGetFactionOfParent 1
 m_bAllowGetArsenalFromParent 1
}