S7R_LoadArsenalLoadout {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AD14F7A2D6CAFD}" {
  Name "Load Base 7R Loadout"
 }
 ActionTitle "LoadBase7RLoadout"
 "Sort Priority" 300
 m_bAllowGetFactionOfParent 1
 m_sS7RSlotId "Base7R"
 m_sS7RLoadoutLabel "Base 7R"
}