S7R_LoadArsenalLoadout {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AD14F7EAE8F099}" {
  Name "Load 7R Loadout"
 }
 ActionTitle "Load7RLoadout"
 "Sort Priority" 200
 m_bAllowGetFactionOfParent 1
 m_sS7RSlotId "Loadout7R"
 m_sS7RLoadoutLabel "Loaout 1"
}