SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{65A9434F43FC50EA}" {
  m_sCategoryDisplayText "#S7R-Menu_Title"
  m_sImageset "{2EFEA2AF1F38E7F0}UI/Textures/Icons/icons_wrapperUI-64.imageset"
  m_bShowOnMap 1
 }
}