SCR_PlayerCommandingMenuActionsSetup {
 m_aActionConfigPairs {
  SCR_PlayerCommandingConfigActionPair "{65A9434F61856758}" {
   m_sActionName "Open7RMenu"
   m_sCommandingMenuConf "{DB8FCDB09B7C98B9}Configs/Commanding/Actions7RMenu.conf"
  }
 }
}