SCR_MissionHeader {
 World "{292FD8A2B20A0400}worlds/HelloWorldMission/HelloWorldMission.ent"
 m_sName "[7R] Hello World"
 m_sAuthor "Flinja"
 m_sDescription "The first test mission with the initial version of all 7R add-ons"
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_sBriefingConfig "{46A5896224556F87}Configs/Briefings/HelloWorldBriefing.conf"
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 50
}