StringTable {
 ItemClassName "DefaultStringTableItem"
 Items {
  DefaultStringTableItem "{659322B7140E8EFA}" {
   Id "S7R-Loadouts_Load7RLoadout"
   Target_en_us "Load 7R Loadout"
  }
  DefaultStringTableItem "{65AD14F4AD160C0A}" {
   Id "S7R-Loadouts_LoadBase7RLoadout"
   Target_en_us "Load Base 7R Loadout"
  }
  DefaultStringTableItem "{659322B72E3166E8}" {
   Id "S7R-Loadouts_SaveLoadout"
   Target_en_us "Save Loadout"
  }
 }
}