S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB63CD17842}" {
  Name "Pick Platoon MMG"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon MMG"
 "Sort Priority" 11
 m_eRole PlatoonMMG
}