S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB630C0C3F8}" {
  Name "Pick Platoon MMG Assistant"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon MMG Assistant"
 "Sort Priority" 12
 m_eRole PlatoonMMGAsst
}