S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB78E8FE4A3}" {
  Name "Pick Platoon Engineer (EOD)"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon Platoon Engineer (EOD)"
 "Sort Priority" 10
 m_eRole PlatoonEngEOD
}