S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB3277D8446}" {
  Name "Pick Platoon Leader"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon Leader"
 "Sort Priority" 1
}