S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB750BEC597}" {
  Name "Pick Platoon AR"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon AR"
 "Sort Priority" 4
 m_eRole PlatoonAR
}