S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB60850C5C4}" {
  Name "Pick Platoon MAT"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon MAT"
 "Sort Priority" 13
 m_eRole PlatoonMAT
}