S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB7A6542015}" {
  Name "Pick Platoon Engineer (Demo)"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon Platoon Engineer (Demo)"
 "Sort Priority" 9
 m_eRole PlatoonEngDemo
}