S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB74A8CB57D}" {
  Name "Pick Platoon Leader"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon Leader"
 "Sort Priority" 3
 m_eRole PlatoonDMR
}