S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB606CDB787}" {
  Name "Pick Platoon HAT"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon HAT"
 "Sort Priority" 15
 m_eRole PlatoonHAT
}