S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB79A9328BD}" {
  Name "Pick Platoon Engineer (Repair)"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon Platoon Engineer (Repair)"
 "Sort Priority" 8
 m_eRole PlatoonEngRepair
}