S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB75EFB497C}" {
  Name "Pick Platoon Driver"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon Driver"
 "Sort Priority" 17
 m_eRole PlatoonDriver
}