S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB62C14FFA7}" {
  Name "Pick Platoon FAC"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon FAC"
 "Sort Priority" 5
 m_eRole PlatoonFAC
}