S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB621651FD1}" {
  Name "Pick Platoon UAV Operator"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon UAV Operator"
 "Sort Priority" 6
 m_eRole PlatoonUAV
}