S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB330C2EB41}" {
  Name "Pick Platoon Medic"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon Medic"
 "Sort Priority" 2
 m_eRole PlatoonMedic
}