S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB63561799F}" {
  Name "Pick Platoon MAT Assistant"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon MAT Assistant"
 "Sort Priority" 14
 m_eRole PlatoonMATAsst
}