S7R_SetPlatoonRoleAction {
 ParentContextList {
  "default"
 }
 UIInfo SCR_ActionUIInfo "{65AC7EB61AE66A3E}" {
  Name "Pick Platoon HAT Assistant"
  m_sIconName "weapons"
 }
 ActionTitle "Platoon HAT Assistant"
 "Sort Priority" 16
 m_eRole PlatoonHATAsst
}