S7R_FactionLoadouts : "{EC2C5F995DB49D9D}Configs/Loadouts/7R/S7R_BaseFactionLoadouts7R.conf" {
 m_7RFaction USVanilla
 m_aSquadRoles {
  S7R_PlayerSquadLoadout "{659B011E855275F6}" {
   m_sLoadoutResource "{0324D04952BEFD47}Prefabs/Characters/7R/US_Vanilla/SquadLoadouts/Character_US_Vanilla_SquadLeader_7R.et"
   m_sLoadoutImage "{E66FEBD3F049BF7D}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_SL.edds"
  }
  S7R_PlayerSquadLoadout "{659B011EE98C4528}" {
   m_sLoadoutResource "{89AF2D2B73F1D920}Prefabs/Characters/7R/US_Vanilla/SquadLoadouts/Character_US_Vanilla_CombatMedic_7R.et"
   m_sLoadoutImage "{8D3E9B959DCE2B60}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Medic.edds"
  }
  S7R_PlayerSquadLoadout "{659B011EE53D141E}" {
   m_sLoadoutResource "{36170B3D1BD398BE}Prefabs/Characters/7R/US_Vanilla/SquadLoadouts/Character_US_Vanilla_Squad_Rifleman_7R.et"
   m_sLoadoutImage "{2B0877799B9B6C66}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_Rifleman.edds"
  }
  S7R_PlayerSquadLoadout "{659B011EF524DDBF}" {
   m_sLoadoutResource "{A9DE327F909D7ACB}Prefabs/Characters/7R/US_Vanilla/SquadLoadouts/Character_US_Vanilla_Squad_AR_7R.et"
   m_sLoadoutImage "{43EA535E240F0B17}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_AR.edds"
  }
  S7R_PlayerSquadLoadout "{659B011EC7FC6EFE}" {
   m_sLoadoutResource "{0201DAA60CACF0EC}Prefabs/Characters/7R/US_Vanilla/SquadLoadouts/Character_US_Vanilla_Squad_LAT_7R.et"
   m_sLoadoutImage "{278C426C1D3B4C27}UI/Textures/EditorPreviews/Characters/BLUFOR/US_Army/Character_US_LAT.edds"
  }
 }
 m_BigBox S7R_BigBox "{659B5A70185ACA55}" : "{911B0AA9B4046050}Configs/Loadouts/7R/US_Vanilla/US_Vanilla_BigBox_7R.conf" {
 }
 m_SupplyBoxes S7R_SupplyBoxLoadouts "{659E9812F0A6AE72}" : "{3015269492ABCDBF}Configs/Loadouts/7R/US_Vanilla/US_Vanilla_SupplyBoxes_7R.conf" {
 }
}