SCR_PlayerCommandingMenuConfig {
 m_RootCategory SCR_PlayerCommandingMenuCategoryElement "{65A9434F43FC50EA}" {
  m_aElements {
   SCR_PlayerCommandingMenuCommand "{65A95C5A8BEE5027}" {
    m_sCommandName "DeployRally"
   }
  }
 }
}