SCR_PlayerCommandsConfig {
 m_aCommands {
  S7R_DeployRallyCommand "{65A95C5BBE56A62A}" {
   m_sCommandName "DeployRally"
   m_sCommandDisplayName "#S7R-Reinsertion_DeployRally"
   m_sIconName "squad"
   m_bShowOnMap 1
   m_iGestureID 1
   m_bPlayAIResponse 0
   m_sRallyEntity "{335835EA5804CC80}Prefabs/7R/Systems/RallyTent7R.et"
  }
 }
}