StringTable {
 ItemClassName "DefaultStringTableItem"
 Items {
  DefaultStringTableItem "{6594F62936C32BA2}" {
   Id "S7R-Callsign_AlphaSquad"
   Target_en_us "Alpha"
  }
  DefaultStringTableItem "{6594F62AE61E960D}" {
   Id "S7R-Callsign_Char_AlphaSL"
   Target_en_us "Alpha SL"
  }
  DefaultStringTableItem "{6594F62AFA99EF29}" {
   Id "S7R-Callsign_Char_BravoSL"
   Target_en_us "Delta SL"
  }
  DefaultStringTableItem "{6594F62AFEF31FCB}" {
   Id "S7R-Callsign_Char_CharlieSL"
   Target_en_us "Charlie SL"
  }
  DefaultStringTableItem "{6594F62AFDDEC125}" {
   Id "S7R-Callsign_Char_DeltaSL"
   Target_en_us "Delta SL"
  }
  DefaultStringTableItem "{6594F62AF03B5281}" {
   Id "S7R-Callsign_Char_Echo1Lead"
   Target_en_us "Echo-1 SL"
  }
  DefaultStringTableItem "{6594F62AF61D823F}" {
   Id "S7R-Callsign_Char_Echo2Lead"
   Target_en_us "Echo-2 SL"
  }
  DefaultStringTableItem "{6594F62AEE6E31BF}" {
   Id "S7R-Callsign_Char_PL"
   Target_en_us "PL"
  }
  DefaultStringTableItem "{6594F62AE0C0D1B8}" {
   Id "S7R-Callsign_Char_Sergeant"
   Target_en_us "SGT"
  }
  DefaultStringTableItem "{6594F62ACBE44DB0}" {
   Id "S7R-Callsign_Char_Sierra1Lead"
   Target_en_us "Sierra-1 SL"
  }
  DefaultStringTableItem "{6594F62AC8C8A3BF}" {
   Id "S7R-Callsign_Char_Sierra2Lead"
   Target_en_us "Sierra-2 SL"
  }
  DefaultStringTableItem "{6594F6291CD9A99D}" {
   Id "S7R-Callsign_Company_A"
   Target_en_us "1st Company"
  }
  DefaultStringTableItem "{6594F6291D6FB0EE}" {
   Id "S7R-Callsign_Company_B"
   Target_en_us "2nd Company"
  }
  DefaultStringTableItem "{6594F62913CEEE83}" {
   Id "S7R-Callsign_Company_C"
   Target_en_us "3rd Company"
  }
  DefaultStringTableItem "{6594F629133FDC38}" {
   Id "S7R-Callsign_Company_D"
   Target_en_us "4th Company"
  }
  DefaultStringTableItem "{6594F629B1E84874}" {
   Id "S7R-Callsign_Platoon_1"
   Target_en_us "1st Platoon"
  }
  DefaultStringTableItem "{6594F629B6CA1A12}" {
   Id "S7R-Callsign_Platoon_2"
   Target_en_us "2nd Platoon"
  }
  DefaultStringTableItem "{6594F629B771428B}" {
   Id "S7R-Callsign_Platoon_3"
   Target_en_us "3rd Platoon"
  }
  DefaultStringTableItem "{6594F629B443B48E}" {
   Id "S7R-Callsign_Platoon_4"
   Target_en_us "4th Platoon"
  }
  DefaultStringTableItem "{6594F62A3D18D787}" {
   Id "S7R-Callsign_Squad_Alpha"
   Target_en_us "Alpha Squad"
  }
  DefaultStringTableItem "{6594F62A3378C7DF}" {
   Id "S7R-Callsign_Squad_Bravo"
   Target_en_us "Bravo Squad"
  }
  DefaultStringTableItem "{6594F62A31861D4C}" {
   Id "S7R-Callsign_Squad_Charlie"
   Target_en_us "Charlie Squad"
  }
  DefaultStringTableItem "{6594F62A3787DAAA}" {
   Id "S7R-Callsign_Squad_Delta"
   Target_en_us "Delta Squad"
  }
  DefaultStringTableItem "{6594F62A0A8B9A3F}" {
   Id "S7R-Callsign_Squad_Echo_1"
   Target_en_us "Echo-1"
  }
  DefaultStringTableItem "{6594F62A0B7EDAB5}" {
   Id "S7R-Callsign_Squad_Echo_2"
   Target_en_us "Echo-2"
  }
  DefaultStringTableItem "{6594F62A3FCDFC9C}" {
   Id "S7R-Callsign_Squad_Platoon"
   Target_en_us "Platoon"
  }
  DefaultStringTableItem "{6594F62A00D5F363}" {
   Id "S7R-Callsign_Squad_Sierra_1"
   Target_en_us "Sierra-1"
  }
  DefaultStringTableItem "{6594F62A0038EBEE}" {
   Id "S7R-Callsign_Squad_Sierra_2"
   Target_en_us "Sierra-2"
  }
  DefaultStringTableItem "{6594F62CEB0DD7EC}" {
   Id "S7R-Groupdesc_AlphaSquad"
   Target_en_us "Alpha Squad of 1st platoon"
  }
  DefaultStringTableItem "{6594F62CEEB88A7C}" {
   Id "S7R-Groupdesc_BravoSquad"
   Target_en_us "Bravo Squad of 1st platoon"
  }
  DefaultStringTableItem "{6594F62CEC9BBCE9}" {
   Id "S7R-Groupdesc_CharlieSquad"
   Target_en_us "Charlie Squad of 1st platoon"
  }
  DefaultStringTableItem "{6594F62CE24C08BC}" {
   Id "S7R-Groupdesc_DeltaSquad"
   Target_en_us "Delta Squad of 1st platoon"
  }
  DefaultStringTableItem "{6594F62CE0316F8E}" {
   Id "S7R-Groupdesc_Echo1"
   Target_en_us "First Fire Support Element of 1st platoon"
  }
  DefaultStringTableItem "{6594F62CE660B8B4}" {
   Id "S7R-Groupdesc_Echo2"
   Target_en_us "Second Fire Support Element of 1st platoon"
  }
  DefaultStringTableItem "{6594F62D6CE0A7BB}" {
   Id "S7R-Groupdesc_PlatoonElement"
   Target_en_us "Lead Element of 1st Platoon"
  }
  DefaultStringTableItem "{6594F62CE55447FC}" {
   Id "S7R-Groupdesc_Sierra1"
   Target_en_us "First Recon Element of 1st platoon"
  }
  DefaultStringTableItem "{6594F62CFBEDB56C}" {
   Id "S7R-Groupdesc_Sierra2"
   Target_en_us "Second Recon Element of 1st platoon"
  }
  DefaultStringTableItem "{6594F62C6D822225}" {
   Id "S7R-Groupname_AlphaSquad"
   Target_en_us "Alpha Squad"
  }
  DefaultStringTableItem "{6594F62C61293DAF}" {
   Id "S7R-Groupname_BravoSquad"
   Target_en_us "Bravo Squad"
  }
  DefaultStringTableItem "{6594F62C643CD552}" {
   Id "S7R-Groupname_CharlieSquad"
   Target_en_us "Charlie Squad"
  }
  DefaultStringTableItem "{6594F62C7BE9FF67}" {
   Id "S7R-Groupname_DeltaSquad"
   Target_en_us "Delta Squad"
  }
  DefaultStringTableItem "{6594F62CAB6359AB}" {
   Id "S7R-Groupname_Echo1"
   Target_en_us "Echo-1 Element"
  }
  DefaultStringTableItem "{6594F62CA80A3F24}" {
   Id "S7R-Groupname_Echo2"
   Target_en_us "Echo-2 Element"
  }
  DefaultStringTableItem "{6594F62C68C9D2B3}" {
   Id "S7R-Groupname_PlatoonElement"
   Target_en_us "Platoon Element"
  }
  DefaultStringTableItem "{6594F62CAFABEE9D}" {
   Id "S7R-Groupname_Sierra1"
   Target_en_us "Sierra-1 Element"
  }
  DefaultStringTableItem "{6594F62CAC73B903}" {
   Id "S7R-Groupname_Sierra2"
   Target_en_us "Sierra-2 Element"
  }
  DefaultStringTableItem "{6592974670D3D2F5}" {
   Id "S7R-Name"
   Target_en_us "7th Rangers Group"
  }
  DefaultStringTableItem "{65929745788F17D4}" {
   Id "S7R-Open7RMenu"
   Target_en_us "Open 7R Menu"
  }
  DefaultStringTableItem "{65929746588EFF43}" {
   Id "S7R-ShortName"
   Target_en_us "7R"
  }
 }
}