S7R_VehicleLoadouts {
 m_aVehicleLoadouts {
  S7R_StructVehicleLoadout "{65AC7EA63134AC08}" {
   m_eVehicleType InfantryVic
  }
  S7R_StructVehicleLoadout "{65AC7EA60BBF85CE}" {
   m_eVehicleType CommandVic
  }
  S7R_StructVehicleLoadout "{65AC7EA609215A11}" {
   m_eVehicleType EchoMATVic
  }
  S7R_StructVehicleLoadout "{65AC7EA60CFBAA3E}" {
   m_eVehicleType EchoHATVic
  }
  S7R_StructVehicleLoadout "{65AC7EA6038593A8}" {
   m_eVehicleType EchoMMGVic
  }
  S7R_StructVehicleLoadout "{65AC7EA60107EB0E}" {
   m_eVehicleType EchoMortarVic
  }
  S7R_StructVehicleLoadout "{65AC7EA604AF9EB7}" {
   m_eVehicleType SierraVic
  }
  S7R_StructVehicleLoadout "{65AC7EA6185A0BB2}" {
   m_eVehicleType FoxtrotAPC
  }
  S7R_StructVehicleLoadout "{65AC7EA61FC2091C}" {
   m_eVehicleType FoxtrotIFV
  }
  S7R_StructVehicleLoadout "{65AC7EA612CB18C8}" {
   m_eVehicleType FoxtrotMBT
  }
  S7R_StructVehicleLoadout "{65AC7EA610486F0D}" {
   m_eVehicleType MikeVic
  }
 }
}