S7R_BigBox {
 m_aItems {
  S7R_StructPrefabAmount "{65AC7EA0EA7937D0}" {
   m_Item "{06D722FC2666EB83}Prefabs/Weapons/Magazines/Box_556x45_M249_200rnd_4Ball_1Tracer.et"
   m_iAmount 60
  }
  S7R_StructPrefabAmount "{65AC7EA0EA7937D9}" {
   m_Item "{4D2C1E8F3A81F894}Prefabs/Weapons/Magazines/Box_762x51_M60_100rnd_4Ball_1Tracer.et"
   m_iAmount 40
  }
  S7R_StructPrefabAmount "{65AC7EA0EA7937DF}" {
   m_Item "{9C05543A503DB80E}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Ball.et"
   m_iAmount 20
  }
  S7R_StructPrefabAmount "{65AC7EA0EA7937DC}" {
   m_Item "{9C5C20FB0E01E64F}Prefabs/Weapons/Launchers/M72/Launcher_M72A3.et"
   m_iAmount 20
  }
  S7R_StructPrefabAmount "{65AC7EA0EA7937A2}" {
   m_Item "{33CBDE73AB48172A}Prefabs/Weapons/Explosives/DemoBlock_M112/DemoBlock_M112.et"
   m_iAmount 20
  }
 }
}